AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - _snippets/*

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile

