---
development:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db
  # Application
  API_HOST: http://localhost:9000

test:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  # Application
  API_HOST: http://localhost:9090

app_test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db

production:
  # API_HOST: https://mind-map.herokuapp.com
