---
 # Name the file secrets.yml
 
development:
  GITHUB_TOKEN: erg9ji4jri4ji4j5i4jsdjoijammdddd25f3aa14

test:
  GITHUB_TOKEN: erg9ji4jri4ji4j5i4jsdjoijammdddd25f3aa14

production:
  GITHUB_TOKEN: erg9ji4jri4ji4j5i4jsdjoijammdddd25f3aa14